---
- name: Config vhost from a template
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/{{ ansible_facts['domain'] }}.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

