---
- name: Set up Apache2
  hosts: nodes
  tasks: 
  - name: Install httpd package
    yum:
      name: httpd
      state: present
  - name: Check httpd service is enabled and it is started
    service:
      name: httpd
      enabled: yes
      state: started
  - name: Create index.html file
    copy:
      content: 'Welcome to my web server'
      dest: /var/www/html/index.html
  - name: Set permission to index.html
    file:
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: '0644'
  - name: Open tcp port 80
    firewalld:
      zone: public
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - https
      - http
 
