---
- name: Uninstall Apache2
  hosts: nodes
  tasks: 
  - name: Uninstall httpd package
    yum:
      name: httpd
      state: absent
  - name: Close tcp port 80
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: disabled
  - name: Remove index.html file
    file:
      path: /var/www/html/index.html
      state: absent
